#!/usr/bin/env python3
"""
Pack OTClient minimap block files (.mmz) into a single .otmm file.

This script expects .mmz files generated by OTClient minimap saving logic:
  minimap_<z>_<blockIndex>.mmz
"""

from __future__ import annotations

import argparse
import os
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

OTMM_SIGNATURE = 0x4D4D544F  # 'OTMM' in little-endian stream writes
OTMM_VERSION = 1
INVALID_POS_MARKER = (0xFFFF, 0xFFFF, 0xFF)

MMZ_FILE_RE = re.compile(r"^minimap_(\d+)_(\d+)\.mmz$")


@dataclass(frozen=True)
class MinimapBlockRecord:
    path: Path
    z: int
    index: int
    x: int
    y: int
    payload: bytes


def parse_mmz(path: Path) -> MinimapBlockRecord:
    raw = path.read_bytes()
    if len(raw) < 12:
        raise ValueError(f"{path} is too small to be a valid mmz block")

    x, y, z, length = struct.unpack_from("<HHBH", raw, 0)
    data_start = 7
    data_end = data_start + length
    if data_end > len(raw):
        raise ValueError(f"{path} has truncated payload")

    payload = raw[data_start:data_end]
    tail = len(raw) - data_end
    if tail >= 5:
        end_x, end_y, end_z = struct.unpack_from("<HHB", raw, data_end)
        if (end_x, end_y, end_z) not in (INVALID_POS_MARKER, (0, 0, 0)):
            raise ValueError(f"{path} has invalid end marker")
    elif tail != 0:
        raise ValueError(f"{path} has invalid trailer size ({tail} bytes)")

    match = MMZ_FILE_RE.match(path.name)
    if match:
        file_z = int(match.group(1))
        if file_z != z:
            raise ValueError(f"{path} header z={z} differs from filename z={file_z}")
        index = int(match.group(2))
    else:
        # Keep deterministic ordering if filename is non-standard.
        index = ((y // 32) * (65536 // 32)) + (x // 32)

    return MinimapBlockRecord(path=path, z=z, index=index, x=x, y=y, payload=payload)


def iter_mmz(mmz_dir: Path) -> Iterable[Path]:
    for entry in mmz_dir.iterdir():
        if entry.is_file() and entry.suffix.lower() == ".mmz":
            yield entry


def pack_otmm(records: list[MinimapBlockRecord], output: Path, description: str) -> None:
    description_bytes = description.encode("utf-8")
    if len(description_bytes) > 0xFFFF:
        raise ValueError("description is too large (must fit in uint16)")

    header = bytearray()
    header += struct.pack("<I", OTMM_SIGNATURE)
    # start offset points to the first minimap block after the metadata string.
    start_offset = 4 + 2 + 2 + 4 + 2 + len(description_bytes)
    header += struct.pack("<H", start_offset)
    header += struct.pack("<H", OTMM_VERSION)
    header += struct.pack("<I", 0)  # flags
    header += struct.pack("<H", len(description_bytes))
    header += description_bytes

    body = bytearray()
    for record in records:
        if record.z < 0 or record.z > 255:
            raise ValueError(f"invalid z={record.z} in {record.path}")
        if len(record.payload) == 0 or len(record.payload) > 0xFFFF:
            raise ValueError(f"invalid payload size in {record.path}")

        body += struct.pack("<HHB", record.x, record.y, record.z)
        body += struct.pack("<H", len(record.payload))
        body += record.payload

    # OTMM parser stops when it reads an invalid position.
    body += struct.pack("<HHB", *INVALID_POS_MARKER)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(header + body)


def main() -> int:
    parser = argparse.ArgumentParser(description="Pack minimap .mmz blocks into an OTMM file.")
    parser.add_argument("--mmz-dir", required=True, help="Directory containing minimap_*.mmz files")
    parser.add_argument("--out", required=True, help="Output .otmm path")
    parser.add_argument("--description", default="Generated by minimap_pack_otmm.py", help="OTMM description metadata")
    parser.add_argument("--strict", action="store_true", help="Fail on the first invalid .mmz block")
    args = parser.parse_args()

    mmz_dir = Path(args.mmz_dir).expanduser().resolve()
    out_path = Path(args.out).expanduser().resolve()

    if not mmz_dir.exists() or not mmz_dir.is_dir():
        raise SystemExit(f"mmz directory not found: {mmz_dir}")

    parsed: list[MinimapBlockRecord] = []
    skipped = 0
    for path in iter_mmz(mmz_dir):
        try:
            parsed.append(parse_mmz(path))
        except Exception as exc:  # noqa: BLE001
            if args.strict:
                raise
            skipped += 1
            print(f"[skip] {path.name}: {exc}")

    # Keep a stable write order for deterministic output.
    parsed.sort(key=lambda r: (r.z, r.index, r.x, r.y, os.fspath(r.path)))

    if not parsed:
        raise SystemExit(f"no valid mmz blocks found in: {mmz_dir}")

    pack_otmm(parsed, out_path, args.description)
    print(f"Packed {len(parsed)} blocks into: {out_path}")
    if skipped:
        print(f"Skipped {skipped} invalid blocks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
